//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightIISServices.Entity
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/FlightIISServices.Entity")]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FlightIISServices.Entity.Flight[] FlightListField;
        
        private string MessageField;
        
        private bool StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FlightIISServices.Entity.Flight[] FlightList
        {
            get
            {
                return this.FlightListField;
            }
            set
            {
                this.FlightListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flight", Namespace="http://schemas.datacontract.org/2004/07/FlightIISServices.Entity")]
    public partial class Flight : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AirlineNameField;
        
        private string ArrivalTimeField;
        
        private int AvailableSeatField;
        
        private string DepartureTimeField;
        
        private string DestinationField;
        
        private string FlightClassField;
        
        private string FlightIdField;
        
        private int PriceField;
        
        private double RatingField;
        
        private string SourceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AirlineName
        {
            get
            {
                return this.AirlineNameField;
            }
            set
            {
                this.AirlineNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArrivalTime
        {
            get
            {
                return this.ArrivalTimeField;
            }
            set
            {
                this.ArrivalTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableSeat
        {
            get
            {
                return this.AvailableSeatField;
            }
            set
            {
                this.AvailableSeatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartureTime
        {
            get
            {
                return this.DepartureTimeField;
            }
            set
            {
                this.DepartureTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destination
        {
            get
            {
                return this.DestinationField;
            }
            set
            {
                this.DestinationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightClass
        {
            get
            {
                return this.FlightClassField;
            }
            set
            {
                this.FlightClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightId
        {
            get
            {
                return this.FlightIdField;
            }
            set
            {
                this.FlightIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filter", Namespace="http://schemas.datacontract.org/2004/07/FlightIISServices.Entity")]
    public partial class Filter : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AirlineNameField;
        
        private int EndRangeField;
        
        private double RatingField;
        
        private int StartRangeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AirlineName
        {
            get
            {
                return this.AirlineNameField;
            }
            set
            {
                this.AirlineNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndRange
        {
            get
            {
                return this.EndRangeField;
            }
            set
            {
                this.EndRangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartRange
        {
            get
            {
                return this.StartRangeField;
            }
            set
            {
                this.StartRangeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/FlightIISServices.Entity")]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CustomerIdField;
        
        private string EmailField;
        
        private string FisrtNameField;
        
        private string LastNameField;
        
        private string MobileNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FisrtName
        {
            get
            {
                return this.FisrtNameField;
            }
            set
            {
                this.FisrtNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://schemas.datacontract.org/2004/07/FlightIISServices.Entity")]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CVVField;
        
        private string CardHolderNameField;
        
        private string CardNumberField;
        
        private string validTillMonthAndYearField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CVV
        {
            get
            {
                return this.CVVField;
            }
            set
            {
                this.CVVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardHolderName
        {
            get
            {
                return this.CardHolderNameField;
            }
            set
            {
                this.CardHolderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string validTillMonthAndYear
        {
            get
            {
                return this.validTillMonthAndYearField;
            }
            set
            {
                this.validTillMonthAndYearField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IFlightService")]
public interface IFlightService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetFlightsBySourceDestinationTravellersAndClass" +
        "", ReplyAction="http://tempuri.org/IFlightService/GetFlightsBySourceDestinationTravellersAndClass" +
        "Response")]
    FlightIISServices.Entity.Result GetFlightsBySourceDestinationTravellersAndClass(string source, string destination, string traveller, string flightClass);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/GetFlightsBySourceDestinationTravellersAndClass" +
        "", ReplyAction="http://tempuri.org/IFlightService/GetFlightsBySourceDestinationTravellersAndClass" +
        "Response")]
    System.Threading.Tasks.Task<FlightIISServices.Entity.Result> GetFlightsBySourceDestinationTravellersAndClassAsync(string source, string destination, string traveller, string flightClass);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/FilteringFlights", ReplyAction="http://tempuri.org/IFlightService/FilteringFlightsResponse")]
    FlightIISServices.Entity.Result FilteringFlights(FlightIISServices.Entity.Result result, FlightIISServices.Entity.Filter filter);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/FilteringFlights", ReplyAction="http://tempuri.org/IFlightService/FilteringFlightsResponse")]
    System.Threading.Tasks.Task<FlightIISServices.Entity.Result> FilteringFlightsAsync(FlightIISServices.Entity.Result result, FlightIISServices.Entity.Filter filter);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/AddNewBooking", ReplyAction="http://tempuri.org/IFlightService/AddNewBookingResponse")]
    string AddNewBooking(FlightIISServices.Entity.Flight flight, FlightIISServices.Entity.Customer customer, int travellers);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/AddNewBooking", ReplyAction="http://tempuri.org/IFlightService/AddNewBookingResponse")]
    System.Threading.Tasks.Task<string> AddNewBookingAsync(FlightIISServices.Entity.Flight flight, FlightIISServices.Entity.Customer customer, int travellers);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/CancelBooking", ReplyAction="http://tempuri.org/IFlightService/CancelBookingResponse")]
    string CancelBooking(string bookindId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/CancelBooking", ReplyAction="http://tempuri.org/IFlightService/CancelBookingResponse")]
    System.Threading.Tasks.Task<string> CancelBookingAsync(string bookindId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/SaveCardDetails", ReplyAction="http://tempuri.org/IFlightService/SaveCardDetailsResponse")]
    FlightIISServices.Entity.Result SaveCardDetails(FlightIISServices.Entity.Result result, FlightIISServices.Entity.Card card);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightService/SaveCardDetails", ReplyAction="http://tempuri.org/IFlightService/SaveCardDetailsResponse")]
    System.Threading.Tasks.Task<FlightIISServices.Entity.Result> SaveCardDetailsAsync(FlightIISServices.Entity.Result result, FlightIISServices.Entity.Card card);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IFlightServiceChannel : IFlightService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class FlightServiceClient : System.ServiceModel.ClientBase<IFlightService>, IFlightService
{
    
    public FlightServiceClient()
    {
    }
    
    public FlightServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public FlightServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FlightServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FlightServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public FlightIISServices.Entity.Result GetFlightsBySourceDestinationTravellersAndClass(string source, string destination, string traveller, string flightClass)
    {
        return base.Channel.GetFlightsBySourceDestinationTravellersAndClass(source, destination, traveller, flightClass);
    }
    
    public System.Threading.Tasks.Task<FlightIISServices.Entity.Result> GetFlightsBySourceDestinationTravellersAndClassAsync(string source, string destination, string traveller, string flightClass)
    {
        return base.Channel.GetFlightsBySourceDestinationTravellersAndClassAsync(source, destination, traveller, flightClass);
    }
    
    public FlightIISServices.Entity.Result FilteringFlights(FlightIISServices.Entity.Result result, FlightIISServices.Entity.Filter filter)
    {
        return base.Channel.FilteringFlights(result, filter);
    }
    
    public System.Threading.Tasks.Task<FlightIISServices.Entity.Result> FilteringFlightsAsync(FlightIISServices.Entity.Result result, FlightIISServices.Entity.Filter filter)
    {
        return base.Channel.FilteringFlightsAsync(result, filter);
    }
    
    public string AddNewBooking(FlightIISServices.Entity.Flight flight, FlightIISServices.Entity.Customer customer, int travellers)
    {
        return base.Channel.AddNewBooking(flight, customer, travellers);
    }
    
    public System.Threading.Tasks.Task<string> AddNewBookingAsync(FlightIISServices.Entity.Flight flight, FlightIISServices.Entity.Customer customer, int travellers)
    {
        return base.Channel.AddNewBookingAsync(flight, customer, travellers);
    }
    
    public string CancelBooking(string bookindId)
    {
        return base.Channel.CancelBooking(bookindId);
    }
    
    public System.Threading.Tasks.Task<string> CancelBookingAsync(string bookindId)
    {
        return base.Channel.CancelBookingAsync(bookindId);
    }
    
    public FlightIISServices.Entity.Result SaveCardDetails(FlightIISServices.Entity.Result result, FlightIISServices.Entity.Card card)
    {
        return base.Channel.SaveCardDetails(result, card);
    }
    
    public System.Threading.Tasks.Task<FlightIISServices.Entity.Result> SaveCardDetailsAsync(FlightIISServices.Entity.Result result, FlightIISServices.Entity.Card card)
    {
        return base.Channel.SaveCardDetailsAsync(result, card);
    }
}
